$text = Get-Content wiki.md
$text = $text -ireplace '^==Actions==', '['
$text = $text -ireplace '^{{.*}}$', ''
$text = $text -ireplace '^{{Action', '{'
$text = $text -ireplace '^}}$', '},'
$text = $text -ireplace '^\| image *= *.*$', ''
$text = $text -ireplace '^\| quote *= *.*$', ''
$text = $text -ireplace '^\| name *= *(.*)$', '"n":"$1",'
$text = $text -ireplace '^\| time *= *(\d+)h (\d+)m (\d+)s$', '"d":"PT$1:$2:$3",'
$text = $text -ireplace '"PT(\d):', '"PT0$1:'
$text = $text -ireplace '"PT(\d{2}):(\d):', '"PT$1:0$2:'
$text = $text -ireplace '"PT(\d{2}):(\d{2}):(\d)"', '"PT$1:$2:0$3"'
$text = $text -ireplace '^\| currency *= *(\d+)', '"c":$1,'
$text = $text -ireplace '^\| xp *= *(\d+)', '"x":$1,'
$text = $text -ireplace '^\| animated *= *.*$', ''
$text = $text -ireplace '^\| requirements_level *= *(\d+)?$', '"l":$1,'
$text = $text -ireplace '^\| requirements_character *= *(.+)?$', '"h":"$1",'
$text = $text -ireplace '^\| requirements_building *= *(.+)?$', '"b":"$1",'
$text = $text -ireplace ',\w*}', '\n}'
$text = $text + ']'
$text | Out-File actions.json