/* Character list (77) ------------------------------ */

    game_data['chr_ord'] = ['1','2','3','4','5','6','7','8','9','10','11','12','76','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','77','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55','56','57','58','61','59','60','62','63','64','65','66','67','68','69','70','71','75','72','73','74'];

    game_data['chr_all'] = {
         '1' : [ "Amy",                        null,                 1, 0, 0, [
                    { "n": "Partyboard",                                "d":"P0T00:15:00",  "c": 9,    "x":5,    "l": 1    },
                    { "n": "Spray-On Outfits",                          "d":"P0T00:15:00",  "c": 9,    "x":5,    "l": 1    },
                    { "n": "Charge Her Cellphone",                      "d":"P0T01:00:00",  "c": 35,   "x":23,   "l": 2,   "b": "Planet Express Building"                    },
                    { "n": "Embrace Her Robosexuality",                 "d":"P0T01:00:00",  "c": 35,   "x":23,   "l": 1,   "b": "Robot Arms Apts."                           },
                    { "n": "Keep on Slippin'",                          "d":"P0T01:00:00",  "c": 35,   "x":23,   "l": 3    },
                    { "n": "Read Mini-Golf Digest",                     "d":"P0T01:00:00",  "c": 35,   "x":23,   "l": 4,   "b": "7^11"                                       },
                    { "n": "Paint Her Nails",                           "d":"P0T02:00:00",  "c": 65,   "x":40,   "l": 5,   "b": "O'Zorgnax's Pub"                            },
                    { "n": "Find a Cat Sitter",                         "d":"P0T02:00:00",  "c": 65,   "x":40,   "l": 1,   "h": "Hattie"                                     },
                    { "n": "Pickpocket Amy",                            "d":"P0T02:00:00",  "c": 135,  "x":85,   "l": 1,   "h": "Burglar Bender"                             },
                    { "n": "Trim the Leg Hair",                         "d":"P0T02:00:00",  "c": 135,  "x":85,   "l": 1,   "h": "Leg Mutant"                                 },
                    { "n": "Hang Out with Bad Boys",                    "d":"P0T04:00:00",  "c": 95,   "x":60,   "l": 6,   "b": "O'Zorgnax's Pub"                            },
                    { "n": "Overpay for a Car",                         "d":"P0T04:00:00",  "c": 95,   "x":60,   "l": 1,   "b": "Malfunctioning Eddie's Rocket Car Emporium" },
                    { "n": "Have Amy and Kif Smooch",                   "d":"P0T06:00:00",  "c": 265,  "x":180,  "l": 1,   "h": "Kif"                                        },
                    { "n": "Attend Social Event ",                      "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 3,   "b": "The Hip Joint"                              },
                    { "n": "Curse in Cantonese",                        "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 5,   "b": "Avenue Hotel"                               },
                    { "n": "Drink Girly Cocktail",                      "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 5,   "b": "O'Zorgnax's Pub"                            },
                    { "n": "Get Ripped Off",                            "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 1,   "b": "Rook Takes Pawnshop"                        }
             ] ],
         '2' : [ "Amy",                        "Nightlife",          4, 0, 0, 
                [
                    { "n": "Spend the Night",                           "d":"P0T02:00:00",  "c": 65,   "x":40,   "l": 1,   "b": "Malfunctioning Eddie's Rocket Car Emporium" },
                    { "n": "Walk Barefoot",                             "d":"P0T04:00:00",  "c": 95,   "x":60,   "l": 3,   "b": "7^11"                                       },
                    { "n": "Get Sloppy Drunk",                          "d":"P0T06:00:00",  "c": 125,  "x":85,   "l": 1    },
                    { "n": "Learn New Moves",                           "d":"P0T06:00:00",  "c": 125,  "x":85,   "l": 3,   "b": "City Tower"                                 },
                    { "n": "Dance on the Bar",                          "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 3,   "b": "O'Zorgnax's Pub"                            },
                    { "n": "Keep it Classy",                            "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 7,   "b": "Cavern on the Green"                        },
                    { "n": "Pass Out",                                  "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 6,   "b": "Electric Ladyland"                          },
                    { "n": "Sit at Hotel Bar",                          "d":"P0T08:00:00",  "c": 155,  "x":105,  "l": 7,   "b": "Avenue Hotel"                               }
                ] 
            ],
         '3' : [ "Amy",                        "Amazonian",          0, 0, 1, 
                [
                    { "n":"Make Out",                                   "d":"P0T01:00:00",  "c":95,   "x":60,   "l":1,    "h":"Kif",                                        },
                    { "n":"Perform for Office Party",                   "d":"P0T02:00:00",  "c":65,   "x":40,   "l":4,    },
                    { "n":"Eat Meat",                                   "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1,    },
                    { "n":"Do the Stilt Walker",                        "d":"P0T04:00:00",  "c":95,   "x":60,   "l":7,    },
                    { "n":"Eat Primitive Snacks",                       "d":"P0T05:00:00",  "c":110,  "x":73,   "l":2,    },
                    { "n":"Stay Up to the Task",                        "d":"P0T06:00:00",  "c":125,  "x":85,   "l":10,   },
                    { "n":"Shop for Taller Stilts",                     "d":"P0T07:00:00",  "c":140,  "x":93,   "l":5,    },
                    { "n":"Lose Her Balance",                           "d":"P0T08:00:00",  "c":155,  "x":105,  "l":3,    },
                    { "n":"Pig Out",                                    "d":"P0T09:00:00",  "c":170,  "x":112,  "l":12,   },
                    { "n":"Go Clubbing",                                "d":"P0T10:00:00",  "c":180,  "x":119,  "l":9,    },
                    { "n":"Enjoy the View",                             "d":"P0T12:00:00",  "c":200,  "x":130,  "l":8,    },
                    { "n":"Refused Service",                            "d":"P0T16:00:00",  "c":230,  "x":150,  "l":7,    },
                    { "n":"Watch Her Step",                             "d":"P0T18:00:00",  "c":250,  "x":164,  "l":6,    },
                    { "n":"Remove Her Make Up",                         "d":"P1T00:00:00",  "c":300,  "x":195,  "l":11,   }
                ]
            ],
         '4': ["Ben Franklin", null, 1, 0, 0,
                [
                    { "n":"Fly a Kite",                                 "d":"P0T02:00:00",  "c":64,   "x":40,   "l":1     },
                    { "n":"Admire the Ladybots",                        "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Defend Himself",                             "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1     },
                    { "n":"Make New Discoveries",                       "d":"P0T05:00:00",  "c":110,  "x":75,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Shop for Turkeys",                           "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1,    "b":"7^11"                                        },
                    { "n":"Marvel at Technology",                       "d":"P0T07:00:00",  "c":140,  "x":93,   "l":1,    "b":"Robot Arms Apts."                            },
                    { "n":"Drink Like an Elder Statesman",              "d":"P0T08:00:00",  "c":155,  "x":105,  "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Sign Important Documents",                   "d":"P0T10:00:00",  "c":180,  "x":119,  "l":1,    "b":"NNYPD Precint"                               }
                ]
            ],
         '5' : [ "Bender",                     null,                 2, 0, 0, 
                [
                    { "n":"Instigate a Bar Fight",                      "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Recharge His Battery",                       "d":"P0T01:00:00",  "c":35,   "x":23,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Shoplift for Fun",                           "d":"P0T01:00:00",  "c":35,   "x":23,   "l":4,    "b":"7^11"                                        },
                    { "n":"Zoom In",                                    "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1     },
                    { "n":"Bend Girders",                               "d":"P0T02:00:00",  "c":65,   "x":40,   "l":5     },
                    { "n":"Get It on with Robot Cars",                  "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Play the Game of Seduction",                 "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1,    "h":"Crushinator"                                 },
                    { "n":"Watch \"All My Circuits\"",                  "d":"P0T02:00:00",  "c":65,   "x":40,   "l":5,    "b":"Planet Express Building"                     },
                    { "n":"Go for a Spin",                              "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1     },
                    { "n":"Receive a Laptop Dance",                     "d":"P0T02:00:00",  "c":65,   "x":40,   "l":5,    "b":"Electric Ladyland"                           },
                    { "n":"Eat Hot Pockets",                            "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1,    "h":"Bachelor Fry"                                },
                    { "n":"Fall on His Back",                           "d":"P0T04:00:00",  "c":95,   "x":60,   "l":6     },
                    { "n":"Plot a Heist",                               "d":"P0T04:00:00",  "c":95,   "x":60,   "l":6,    "b":"Avenue Hotel"                                },
                    { "n":"Vandalize Property",                         "d":"P0T04:00:00",  "c":95,   "x":60,   "l":6,    "b":"City Tower"                                  },
                    { "n":"Take Some Snaps",                            "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1     },
                    { "n":"Raid Liquor Cabinets",                       "d":"P0T08:00:00",  "c":155,  "x":105,  "l":7,    "b":"Avenue Hotel"                                },
                    { "n":"Run a Scam Dating Service",                  "d":"P0T08:00:00",  "c":155,  "x":105,   "l":1,   "b":"Modest Business Building"                    },
                    { "n":"Pawn Stolen Heirlooms",                      "d":"P0T08:00:00",  "c":155,  "x":105,   "l":1,   "b":"Rook Takes Pawnshop"                         },
                    { "n":"Avoid Responsibility",                       "d":"P0T08:00:00",  "c":155,  "x":105,  "l":7,    "b":"Modest Business Building"                    }
                ]
            ],
         '6' : [ "Bender",                     "Bee",                4, 0, 1, 
                [
                    { "n":"Bee Dance",                                  "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Botching a Delivery",                        "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    "b":"Planet Express Building"                     },
                    { "n":"Pick Up Some Honey",                         "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1,    "b":"7^11"                                        },
                    { "n":"Sell Honey",                                 "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1     },
                    { "n":"Swell the Belly with Nectar",                "d":"P0T05:00:00",  "c":110,  "x":73,   "l":2,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Hang Out at the Hive",                       "d":"P0T06:00:00",  "c":125,  "x":85,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Take a Queen",                               "d":"P0T08:00:00",  "c":155,  "x":105,  "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Sting Someone in Self Defense",              "d":"P0T10:00:00",  "c":180,  "x":119,  "l":6,    "b":"Avenue Hotel"                                },
                    { "n":"Get a Buzz Cut",                             "d":"P0T12:00:00",  "c":200,  "x":130,  "l":5,    "b":"City Tower"                                  },
                    { "n":"Look for a Queen Bee",                       "d":"P0T16:00:00",  "c":230,  "x":150,  "l":7,    "b":"Electric Ladyland"                           },
                    { "n":"Run a Sting Operation",                      "d":"P0T18:00:00",  "c":250,  "x":164,  "l":8,    "b":"NNYPD Precinct"                              },
                    { "n":"Admire the Work of Pablo Bee-caso",          "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"Museum of Really Modern Art"                 }
                ]
            ],
         '7' : [ "Bender",                     "Burglar",            2, 0, 0, 
                [
                    { "n":"Open Money Bags",                            "d":"P0T01:00:00",  "c":35,   "x":23,   "l":3     },
                    { "n":"Break into Fry's Apartment",                 "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    "b":"Robot Arms Apts."                            },
                    { "n":"Pickpocket Amy",                             "d":"P0T02:00:00",  "c":135,  "x":85,   "l":1,    "h":"Amy"                                         },
                    { "n":"Burgle Guests",                              "d":"P0T04:00:00",  "c":95,   "x":60,   "l":6,    "b":"Avenue Hotel"                                },
                    { "n":"Get a 3-Finger Discount",                    "d":"P0T04:00:00",  "c":95,   "x":60,   "l":5,    "b":"7^11"                                        },
                    { "n":"Scale Building with Suction Cups",           "d":"P0T04:00:00",  "c":95,   "x":60,   "l":13,   "b":"Skyscraper Center"                           },
                    { "n":"Sell Booty",                                 "d":"P0T04:00:00",  "c":95,   "x":60,   "l":8,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Steal the Free Mints",                       "d":"P0T04:00:00",  "c":95,   "x":60,   "l":11,   "b":"Cavern on the Green"                         },
                    { "n":"Destroy Evidence",                           "d":"P0T08:00:00",  "c":155,  "x":105,  "l":9,    "b":"NNYPD Precinct"                              },
                    { "n":"Raid Coworkers' Cubbies",                    "d":"P0T08:00:00",  "c":155,  "x":105,  "l":7,    "b":"Planet Express Building"                     },
                    { "n":"Raid the League of Robots",                  "d":"P0T08:00:00",  "c":155,  "x":105,  "l":12,   "b":"City Tower"                                  },
                    { "n":"Smuggle Blood Diamonds",                     "d":"P0T08:00:00",  "c":155,  "x":105,  "l":15,   "b":"Diamonds are Forever"                        },
                    { "n":"Steal Hearts",                               "d":"P0T08:00:00",  "c":155,  "x":105,  "l":10,   "b":"Electric Ladyland"                           },
                    { "n":"Submit Burglary Form 22-JZX",                "d":"P0T08:00:00",  "c":155,  "x":105,  "l":14,   "b":"Central Bureaucracy"                         }
                ]
            ],
         '8' : [ "Bender",                     "Ghost",              4, 0, 0, 
                [
                    { "n":"Haunt the Stripperbots",                     "d":"P0T01:00:00",  "c":35,   "x":23,   "l":12,   "b":"Electric Ladyland"                           },
                    { "n":"Mess with the Clerk",                        "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    "b":"7^11"                                        },
                    { "n":"Sulk at Home",                               "d":"P0T02:00:00",  "c":65,   "x":40,   "l":10,   "b":"Robot Arms Apts."                            },
                    { "n":"Look for Friends",                           "d":"P0T03:00:00",  "c":80,   "x":54,   "l":7,    "b":"Planet Express Building"                     },
                    { "n":"Freak Out",                                  "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Carnival Tent"                               },
                    { "n":"Scream for Attention",                       "d":"P0T05:00:00",  "c":110,  "x":73,   "l":20,   "b":"City Tower"                                  },
                    { "n":"Curse in the Night",                         "d":"P0T06:00:00",  "c":125,  "x":85,   "l":3,    "b":"Planet Express Building"                     },
                    { "n":"Start the Engines",                          "d":"P0T07:00:00",  "c":140,  "x":93,   "l":14,   "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Drink Spirits",                              "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    },
                    { "n":"Harass the Guests",                          "d":"P0T09:00:00",  "c":170,  "x":112,  "l":22,   "b":"Avenue Hotel"                                },
                    { "n":"Scare Some Citizens",                        "d":"P0T10:00:00",  "c":180,  "x":119,  "l":9,    },
                    { "n":"Dolphin Dive",                               "d":"P0T12:00:00",  "c":200,  "x":130,  "l":8,    },
                    { "n":"Reach the Top",                              "d":"P0T00:00:00",  "c":0,    "x":0,    "l":24,   "b":"Satellite Building"                          },
                    { "n":"Go Behind the Bar",                          "d":"P0T16:00:00",  "c":230,  "x":150,  "l":4,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Tamper with People's Food",                  "d":"P0T18:00:00",  "c":250,  "x":164,  "l":16,   "b":"Cavern on the Green"                         },
                    { "n":"Scare the Crew",                             "d":"P0T20:00:00",  "c":265,  "x":176,  "l":6,    "b":"Planet Express Building"                     },
                    { "n":"Free Some Convicts",                         "d":"P0T22:00:00",  "c":285,  "x":187,  "l":18,   "b":"NNYPD Precinct"                              }
                ]
            ],
         '9' : [ "Bender",                     "Golden",             4, 0, 0, 
                [
                    { "n":"Make Gold Coins",                            "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1,    },
                    { "n":"Make it Rain",                               "d":"P0T02:00:00",  "c":65,   "x":40,   "l":5,    "b":"Electric Ladyland"                           },
                    { "n":"Purchase Gold Polish",                       "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1,    "b":"7^11"                                        },
                    { "n":"Make a Golden Toast",                        "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Polish Assets",                              "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    },
                    { "n":"Use Himself as Collateral",                  "d":"P0T04:00:00",  "c":95,   "x":60,   "l":7,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Hoard Gold Bricks",                          "d":"P0T08:00:00",  "c":155,  "x":105,  "l":1,    },
                    { "n":"Order the Finest Room Service",              "d":"P0T08:00:00",  "c":155,  "x":105,  "l":10,   "b":"Avenue Hotel"                                },
                    { "n":"Outshine His Coworkers",                     "d":"P0T08:00:00",  "c":155,  "x":105,  "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Request the Pricier Menu",                   "d":"P0T08:00:00",  "c":155,  "x":105,  "l":8,    "b":"Cavern on the Green"                         },
                    { "n":"Blind Guests",                               "d":"P0T12:00:00",  "c":200,  "x":130,  "l":9,    "b":"City Tower"                                  },
                    { "n":"Flash His Wealth",                           "d":"P0T12:00:00",  "c":200,  "x":130,  "l":11,   "b":"Modest Business Building"                    },
                    { "n":"Give Business Ideas",                        "d":"P0T16:00:00",  "c":230,  "x":150,  "l":12,   "b":"Satellite Building"                          },
                    { "n":"Entertain Tourists",                         "d":"P1T00:00:00",  "c":300,  "x":195,  "l":13,   "b":"New New York Plaza"                          }
                ]
            ],
        '10' : [ "Bender",                     "Hunter",             3, 0, 2, 
                [
                    { "n":"Target Practice",                            "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Snub His Nose",                              "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1     },
                    { "n":"Shine His Boots",                            "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Clean His Gun",                              "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Robot Arms Apts."                            },
                    { "n":"Hunt for a Deal",                            "d":"P0T05:00:00",  "c":110,  "x":73,   "l":1,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Enjoy the Finest Game",                      "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1,    "b":"Cavern on the Green"                         },
                    { "n":"Steal Some Bullets",                         "d":"P0T07:00:00",  "c":140,  "x":93,   "l":1,    "b":"NNYPD Precinct"                              },
                    { "n":"Practice Gun Safety",                        "d":"P0T08:00:00",  "c":155,  "x":105,  "l":1,    "b":"New New York Plaza"                          }
                ]
            ],
        '11' : [ "Bender",                     "Pharaoh",            0, 0, 1, 
                [
                    { "n":"Buy Pyramid Lotto Scratchers",               "d":"P0T01:00:00",  "c":35,   "x":23,   "l":2,    "b":"7^11"                                        },
                    { "n":"Communicate with Ancient Aliens",            "d":"P0T02:00:00",  "c":65,   "x":40,   "l":12,   "b":"Satellite Building"                          },
                    { "n":"Drink Mead",                                 "d":"P0T02:00:00",  "c":65,   "x":40,   "l":4,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Walk Like an Egyptian",                      "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1,    },
                    { "n":"Repair His Chariot",                         "d":"P0T04:00:00",  "c":95,   "x":60,   "l":10,   "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Look Down Upon Peons",                       "d":"P0T04:00:00",  "c":95,   "x":60,   "l":13,   "b":"New New York Plaza"                          },
                    { "n":"Recover the Book of the Dead",               "d":"P0T04:00:00",  "c":95,   "x":60,   "l":7,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Make the Professor Eat Mummy Jerky",         "d":"P0T04:00:00",  "c":95,   "x":60,   "l":5,    "b":"Planet Express Building"                     },
                    { "n":"Take a Chariot Ride",                        "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3,    "h":"Fry",                                        },
                    { "n":"Apply Guyliner",                             "d":"P0T08:00:00",  "c":155,  "x":105,  "l":15,   "b":"Avenue Hotel"                                },
                    { "n":"Defy the Laws of Man",                       "d":"P0T08:00:00",  "c":155,  "x":105,  "l":16,   "b":"NNYPD Precinct"                              },
                    { "n":"Dine with Hathor",                           "d":"P0T08:00:00",  "c":155,  "x":105,  "l":9,    "b":"Cavern on the Green"                         },
                    { "n":"Make a Robot Sacrifice",                     "d":"P0T08:00:00",  "c":155,  "x":105,  "l":8,    "b":"Robot Arms Apts."                            },
                    { "n":"Marvel at Modern Pyramids",                  "d":"P0T08:00:00",  "c":155,  "x":105,  "l":14,   "b":"Skyscraper Center"                           },
                    { "n":"Recruit Concubines",                         "d":"P0T08:00:00",  "c":155,  "x":105,  "l":6,    "b":"Electric Ladyland"                           }
                ]
            ],
        '12' : [ "Bender",                     "Ramblin' Rodriguez", 3, 0, 0, 
                [
                    { "n":"Play for Tips",                              "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Perform for the Crew",                       "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    "b":"Planet Express Building"                     },
                    { "n":"Pour Out His Soul",                          "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1     },
                    { "n":"Drink His Pain Away",                        "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Shop for a Beater",                          "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Be the Evening's Entertainment",             "d":"P0T06:00:00",  "c":125,  "x":85,   "l":4,    "b":"Cavern on the Green"                         },
                    { "n":"Serenade the Stripperbots",                  "d":"P0T06:00:00",  "c":125,  "x":85,   "l":7,    "b":"Electric Ladyland"                           },
                    { "n":"Keep His Neighbors Up",                      "d":"P0T06:00:00",  "c":125,  "x":85,   "l":2,    "b":"Robot Arms Apts."                            },
                    { "n":"Buy Back His Guitar",                        "d":"P0T08:00:00",  "c":155,  "x":105,  "l":3,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Play in His Cell",                           "d":"P0T10:00:00",  "c":180,  "x":119,  "l":5,    "b":"NNYPD Precinct"                              },
                    { "n":"Spread His Pain",                            "d":"P0T12:00:00",  "c":200,  "x":130,  "l":6,    "b":"Modest Business Building"                    },
                    { "n":"Sing the Blues",                             "d":"P0T16:00:00",  "c":230,  "x":150,  "l":8,    "b":"Satellite Building"                          },
                    { "n":"Register As a Musician",                     "d":"P0T18:00:00",  "c":250,  "x":164,  "l":9,    "b":"Central Bureaucracy"                         },
                    { "n":"Strum for Tips",                             "d":"P1T00:00:00",  "c":300,  "x":195,  "l":10,   "b":"Avenue Hotel"                                }
                ]
            ],
        '76' : [ "Bender",                     "Santa Claus",        4, 0, 0, 
            ],
        '13' : [ "Bender's Mom",               null,                 2, 0, 1, 
                [
                    { "n":"Defend Flexo",                               "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Look for a Stronger Elbow",                  "d":"P0T01:00:00",  "c":35,   "x":23,   "l":3,    },
                    { "n":"Do Arm Gymnastics",                          "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1     },
                    { "n":"Illicit Stares",                             "d":"P0T02:00:00",  "c":65,   "x":40,   "l":4,    },
                    { "n":"Be Concerned",                               "d":"P0T03:00:00",  "c":80,   "x":54,   "l":1,    "b":"Electric Ladyland"                           },
                    { "n":"Bond With Other Machines",                   "d":"P0T04:00:00",  "c":95,   "x":60,   "l":5,    },
                    { "n":"Taking Top Shelf Snacks",                    "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    },
                    { "n":"Be Refused Service",                         "d":"P0T06:00:00",  "c":125,  "x":85,   "l":6,    },
                    { "n":"Talk About Bender's Birth",                  "d":"P0T06:00:00",  "c":125,  "x":85,   "l":2,    },
                    { "n":"Feel Right at Home",                         "d":"P0T08:00:00",  "c":155,  "x":105,  "l":4,    },
                    { "n":"Work the Yo-yo",                             "d":"P0T08:00:00",  "c":155,  "x":105,  "l":1     },
                    { "n":"Confuse the Officers",                       "d":"P0T10:00:00",  "c":180,  "x":119,  "l":7,    },
                    { "n":"Show Off Assembly Skills",                   "d":"P0T12:00:00",  "c":200,  "x":130,  "l":8,    },
                    { "n":"Run a Demo",                                 "d":"P0T16:00:00",  "c":230,  "x":150,  "l":9,    },
                    { "n":"Try to Get Signal",                          "d":"P1T00:00:00",  "c":300,  "x":195,  "l":10,   }
                ]
            ],
        '14' : [ "Bev",                        null,                 3, 0, 0, 
            ],
        '15' : [ "Bill Nye",                   null,                 1, 0, 1, 
                [
                    { "n":"Knot His Bowtie",                            "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1},
                    { "n":"Make Some Quick Observations",               "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1},
                    { "n":"Research Snacks",                            "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    "b":"7^11"                                        },
                    { "n":"Compare Performance Stats",                  "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Give a Speech About Science",                "d":"P0T03:00:00",  "c":80,   "x":54,   "l":5,    "b":"Avenue Hotel"                                },
                    { "n":"Ask About Science Equipment",                "d":"P0T04:00:00",  "c":95,   "x":60,   "l":8,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Ride Circles Around Farnsworth",             "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "h":"The Professor"                               },
                    { "n":"Assist the Forensics Department",            "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6,    "b":"NNYPD Precinct"                              },
                    { "n":"Drink With Peers",                           "d":"P0T05:00:00",  "c":110,  "x":73,   "l":4,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Cohabitate With Robots",                     "d":"P0T06:00:00",  "c":125,  "x":85,   "l":7,    "b":"Robot Arms Apts."                            },
                    { "n":"Do a Live Experiment",                       "d":"P0T07:00:00",  "c":140,  "x":93,   "l":9,    "b":"City Tower"                                  },
                    { "n":"Marvel at the Natural Ingredients",          "d":"P0T08:00:00",  "c":155,  "x":105,  "l":10,   "b":"Cavern on the Green"                         },
                    { "n":"Fight Against Climate Change",               "d":"P0T10:00:00",  "c":180,  "x":119,  "l":11,   "b":"Modest Business Building"                    },
                    { "n":"Replay His TV Show",                         "d":"P0T12:00:00",  "c":200,  "x":130,  "l":12,   "b":"Satellite Building"                          }
                ]
            ],
        '16' : [ "Billionairebot",             null,                 2, 0, 0, 
                [
                    { "n":"Drink His Money",                            "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1,    },
                    { "n":"Fold Paper Planes",                          "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    },
                    { "n":"Collect Payments",                           "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Cheat the Crew",                             "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Shine His Ring",                             "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3,    },
                    { "n":"Overtip",                                    "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6,    "b":"Electric Ladyland"                           },
                    { "n":"Flash His Obscene Paycheck",                 "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1,    "b":"Diamonds are Forever"                        },
                    { "n":"Toast Wealth",                               "d":"P0T06:00:00",  "c":125,  "x":85,   "l":10,   "b":"O'Zorgnax's Pub"                             },
                    { "n":"Cringe at the Offerings",                    "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"7^11"                                        },
                    { "n":"Buy One of Everything",                      "d":"P0T10:00:00",  "c":180,  "x":119,  "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Purchase a Luxury Vehicle",                  "d":"P0T12:00:00",  "c":200,  "x":130,  "l":7,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Fund Shady Politicians",                     "d":"P0T16:00:00",  "c":230,  "x":150,  "l":15,   "b":"City Tower"                                  },
                    { "n":"Order the Most Expensive Item",              "d":"P0T18:00:00",  "c":250,  "x":164,  "l":8,    "b":"Cavern on the Green"                         },
                    { "n":"Invest His Money",                           "d":"P0T00:00:00",  "c":0,    "x":0,    "l":20,   "b":"Modest Business Building"                    },
                    { "n":"Pay Off Dirty Cops",                         "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"NNYPD Precinct"                              }
                ]
            ],
        '17' : [ "Blatherbot",                 null,                 2, 0, 0, 
                [
                    { "n":"Speak With Amy",                             "d":"P0T01:00:00",  "c":80,   "x":54,   "l":3,    "h":"Amy",                                        },
                    { "n":"Polish Mustache",                            "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    },
                    { "n":"Pontificate Over Pointless Subjects ",       "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Torture the Crew",                           "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Drink Tea",                                  "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    },
                    { "n":"Waste the Dealer's Time",                    "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6,    "b":"Malfunctioning Eddie's Rocket Car Emporium " },
                    { "n":"Blather Over Drinks",                        "d":"P0T06:00:00",  "c":125,  "x":85,   "l":10,   "b":"O'Zorgnax's Pub"                             },
                    { "n":"Discuss the Snack Options",                  "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"7^11"                                        },
                    { "n":"Chat up a Stripperbot",                      "d":"P0T10:00:00",  "c":180,  "x":119,  "l":4,    "b":"Electric Ladyland"                           },
                    { "n":"Take Forever to Order",                      "d":"P0T12:00:00",  "c":200,  "x":130,  "l":7,    "b":"Cavern on the Green"                         },
                    { "n":"Discuss Business Matters",                   "d":"P0T16:00:00",  "c":230,  "x":150,  "l":15,   "b":"Modest Business Building"                    },
                    { "n":"Make His Case",                              "d":"P0T18:00:00",  "c":250,  "x":164,  "l":8,    "b":"NNYPD Precinct"                              },
                    { "n":"Give a Boring Speech",                       "d":"P0T20:00:00",  "c":265,  "x":176,  "l":20,   "b":"New New York Plaza"                          },
                    { "n":"Enjoy a Fine Smoke",                         "d":"P0T22:00:00",  "c":285,  "x":187,  "l":25,   "b":"Hacking Jack's Fine Smokables"               },
                    { "n":"Bother the Hotel Staff",                     "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"Avenue Hotel"                                }
                ]
            ],
        '18' : [ "The Borax Kid",              null,                 0, 0, 1, 
                [
                    { "n":"Reload His Six-Shooter",                     "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Fan Himself",                                "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1     },
                    { "n":"Make Detergent",                             "d":"P0T03:00:00",  "c":80,   "x":54,   "l":4     },
                    { "n":"Pawn Items for Cash",                        "d":"P0T04:00:00",  "c":95,   "x":60,   "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Buy Some Moonshine",                         "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"7^11"                                        },
                    { "n":"Admiring the Ladybots",                      "d":"P0T06:00:00",  "c":125,  "x":85,   "l":5,    "b":"Electric Ladyland"                           },
                    { "n":"Compliment the Robot Domiciles",             "d":"P0T06:00:00",  "c":125,  "x":85,   "l":2,    "b":"Robot Arms Apts."                            },
                    { "n":"Shed Some Flakes",                           "d":"P0T08:00:00",  "c":155,  "x":105,  "l":3,    "b":"Modest Business Building"                    },
                    { "n":"Show Some Hospitality",                      "d":"P0T08:00:00",  "c":155,  "x":105,  "l":2     },
                    { "n":"Ask About the Horsepower",                   "d":"P0T10:00:00",  "c":180,  "x":119,  "l":6,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Settle a Wager",                             "d":"P0T10:00:00",  "c":180,  "x":119,  "l":8,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Eat Fancy City Food",                        "d":"P0T12:00:00",  "c":200,  "x":130,  "l":7,    "b":"Cavern on the Green"                         },
                    { "n":"Ask for the Sheriff",                        "d":"P0T14:00:00",  "c":215,  "x":143,  "l":8,    "b":"NNYPD Precinct"                              },
                    { "n":"Make a Deal",                                "d":"P0T16:00:00",  "c":230,  "x":150,  "l":9,    "b":"City Tower"                                  },
                    { "n":"Get Some Shut Eye",                          "d":"P1T00:00:00",  "c":300,  "x":195,  "l":10,   "b":"Avenue Hotel"                                }
                ]
            ],
        '19' : [ "Boxy",                       null,                 3, 0, 1, 
                [
                    { "n":"Power Back Up",                              "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Point His Gun",                              "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2     },
                    { "n":"Act In a Living Room",                       "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Engage Stealth Mode",                        "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3     },
                    { "n":"Light Up His Eyes",                          "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Steal the Scene",                            "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Pink Skyscraper"                             },
                    { "n":"Beep In Enthusiasm",                         "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6,    "b":"Electric Ladyland"                           },
                    { "n":"Order a Shot of Beep",                       "d":"P0T06:00:00",  "c":125,  "x":85,   "l":10,   "b":"O'Zorgnax's Pub"                             },
                    { "n":"Buy New Batteries",                          "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"7^11"                                        },
                    { "n":"Browse for New Shell",                       "d":"P0T10:00:00",  "c":180,  "x":119,  "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Look for a Boxy Vehicle",                    "d":"P0T12:00:00",  "c":200,  "x":130,  "l":7,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Beep in the Lobby",                          "d":"P0T18:00:00",  "c":250,  "x":164,  "l":8,    "b":"City Tower"                                  },
                    { "n":"Call Calculon",                              "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"Satellite Building"                          }
                ]
            ],
        '20' : [ "Butcher Bot",                null,                 2, 0, 1, 
            ],
        '21' : [ "Calculon",                   null,                 0, 0, 0, 
                [
                    { "n":"Pause Dramatically",                         "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1,    },
                    { "n":"Avoid a Fan Mob",                            "d":"P0T02:00:00",  "c":65,   "x":40,   "l":3,    "b":"7^11"                                        },
                    { "n":"Die on Stage",                               "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    },
                    { "n":"Recharge Acting Unit",                       "d":"P0T02:00:00",  "c":65,   "x":40,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Watch \"All My Circuits\"",                  "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2,    "b":"Planet Express Building"                     },
                    { "n":"Celebrate Himself",                          "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Sell Awards for Money",                      "d":"P0T04:00:00",  "c":95,   "x":60,   "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Leverage Fame for Discounts",                "d":"P0T08:00:00",  "c":155,  "x":105,  "l":3,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Receive VIP Treatment",                      "d":"P0T08:00:00",  "c":155,  "x":105,  "l":6,    "b":"Cavern on the Green"                         },
                    { "n":"Steal the Spotlight",                        "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"Electric Ladyland"                           },
                    { "n":"Visit League of Robots",                     "d":"P0T08:00:00",  "c":155,  "x":105,  "l":4,    "b":"City Tower"                                  }
                ]
            ],
        '22' : [ "Calculon",                   "Ghost",              2, 0, 0, 
                [
                    { "n":"Sword Fight",                                "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Hit the Bottle",                             "d":"P0T02:00:00",  "c":65,   "x":40,   "l":2     },
                    { "n":"Frighten the Tenants",                       "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Give a Haunting Performance",                "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Perform Summoning Ritual",                   "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3     },
                    { "n":"Raise Some Neck Hairs",                      "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6,    "b":"Cavern on the Green"                         },
                    { "n":"Raise His Glass",                            "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Spook the Living",                           "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1,    "b":"Skyscraper Center"                           },
                    { "n":"Scare the Patrons",                          "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"7^11"                                        },
                    { "n":"Sneak Backstage",                            "d":"P0T10:00:00",  "c":180,  "x":119,  "l":4,    "b":"Electric Ladyland"                           },
                    { "n":"Curse the Officers",                         "d":"P0T12:00:00",  "c":200,  "x":130,  "l":7,    "b":"NNYPD Precinct"                              },
                    { "n":"Spread Terror",                              "d":"P0T00:00:00",  "c":0,    "x":0,    "l":15,   "b":"Modest Business Building"                    },
                    { "n":"Recall His Past",                            "d":"P0T18:00:00",  "c":250,  "x":164,  "l":8,    "b":"City Tower"                                  },
                    { "n":"Cause a Heart Attack",                       "d":"P0T00:00:00",  "c":0,    "x":0,    "l":20,   "b":"New New York Plaza"                          },
                    { "n":"Turn off the Lights",                        "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"Avenue Hotel"                                }
                ]
            ],
        '23' : [ "Calculon",                   "Shakespeare",        4, 0, 0, 
                [
                    { "n":"Perform Classical Theater",                  "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Drink Poison",                               "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3     },
                    { "n":"Show Some Emotion",                          "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3,    "b":"Robot Arms Apts."                            },
                    { "n":"Do a Private Performance",                   "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Stopping the Show",                          "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6,    "b":"Electric Ladyland"                           },
                    { "n":"Act Under the Influence",                    "d":"P0T06:00:00",  "c":125,  "x":85,   "l":10,   "b":"O'Zorgnax's Pub"                             },
                    { "n":"Buy Bottled Water",                          "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"7^11"                                        },
                    { "n":"Purchase the Best Props",                    "d":"P0T10:00:00",  "c":180,  "x":119,  "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Shopping for a Buggy",                       "d":"P0T12:00:00",  "c":200,  "x":130,  "l":7,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Perform Dinner Theater",                     "d":"P0T18:00:00",  "c":250,  "x":164,  "l":8,    "b":"Cavern on the Green"                         },
                    { "n":"Make a Public Appearance",                   "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"City Tower"                                  }
                ]
            ],
        '24' : [ "Father Changstein El-Gamal", null,                 4, 0, 1, 
            ],
        '25' : [ "Chris Hardwick",             null,                 0, 0, 2, 
                [
                    { "n":"Book a Clean Shelf",                         "d":"P0T01:00:00",  "c":35,   "x":23,   "l":2     },
                    { "n":"Look for Extra Jar Space",                   "d":"P0T02:00:00",  "c":65,   "x":40,   "l":6     },
                    { "n":"Go On the Air",                              "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1     },
                    { "n":"Decorate His Jar",                           "d":"P0T03:00:00",  "c":80,   "x":54,   "l":3     },
                    { "n":"Do a Stand-Up Set",                          "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3     },
                    { "n":"Fly Like a Superhero",                       "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1     },
                    { "n":"Order the Whole Menu",                       "d":"P0T05:00:00",  "c":110,  "x":73,   "l":6     },
                    { "n":"Binge on Chips",                             "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1     },
                    { "n":"Start a Dog Fight",                          "d":"P0T06:00:00",  "c":125,  "x":85,   "l":5     },
                    { "n":"Host a Trivia Night",                        "d":"P0T08:00:00",  "c":155,  "x":105,  "l":1     },
                    { "n":"Purchase a Jar Dance",                       "d":"P0T08:00:00",  "c":155,  "x":105,  "l":4,    "b":"Electric Ladyland"                           },
                    { "n":"Start a New Hashtag",                        "d":"P0T10:00:00",  "c":180,  "x":119,  "l":7     },
                    { "n":"Control the Microphone",                     "d":"P0T12:00:00",  "c":200,  "x":130,  "l":8     },
                    { "n":"Fly Through the Halls",                      "d":"P0T16:00:00",  "c":230,  "x":150,  "l":9     },
                    { "n":"Nerd Out",                                   "d":"P1T00:00:00",  "c":300,  "x":195,  "l":10,   "b":"Planet Express Building"                     }
                ]
            ],
        '26' : [ "Crushinator",                null,                 4, 0, 1, 
                [
                    { "n":"Ride Low",                                   "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Look for Love",                              "d":"P0T04:00:00",  "c":95,   "x":60,   "l":1,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Eat Her Feelings",                           "d":"P0T02:00:00",  "c":65,   "x":40,   "l":5,    "b":"7^11"                                        },
                    { "n":"Play the Game of Seduction",                 "d":"P0T02:00:00",  "c":65,   "x":40,   "l":1,    "h":"Bender"                                      },
                    { "n":"Look for Large Bumpers",                     "d":"P0T03:00:00",  "c":80,   "x":54,   "l":4,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Crush Rocks",                                "d":"P0T04:00:00",  "c":95,   "x":60,   "l":3     },
                    { "n":"Crush Her Enemies",                          "d":"P0T05:00:00",  "c":110,  "x":73,   "l":3     },
                    { "n":"Flirt with Other Robots",                    "d":"P0T06:00:00",  "c":125,  "x":85,   "l":8     },
                    { "n":"Take Up Space",                              "d":"P0T06:00:00",  "c":125,  "x":85,   "l":1,    "b":"Planet Express Building"                     },
                    { "n":"Shake Her Wide Load",                        "d":"P0T08:00:00",  "c":155,  "x":105,  "l":2     },
                    { "n":"Visit the Penthouse",                        "d":"P0T10:00:00",  "c":180,  "x":119,  "l":4,    "b":"Skyscraper Center"                           },
                    { "n":"Get Appraised",                              "d":"P0T10:00:00",  "c":180,  "x":119,  "l":6,    "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Compress a Diamond",                         "d":"P0T12:00:00",  "c":200,  "x":130,  "l":5,    "b":"Diamonds are Forever"                        },
                    { "n":"Crack Some Lobster Shells",                  "d":"P0T16:00:00",  "c":230,  "x":150,  "l":7,    "b":"Cavern on the Green"                         },
                    { "n":"Report Her Broken Heart",                    "d":"P1T00:00:00",  "c":300,  "x":195,  "l":9,    "b":"NNYPD Precinct"                              }
                ]
            ],
        '27' : [ "Destructor",                 null,                 0, 0, 1, 
                [
                    { "n":"Chase a Butterfly",                          "d":"P0T01:00:00",  "c":35,   "x":23,   "l":1     },
                    { "n":"Break Glasses",                              "d":"P0T02:00:00",  "c":65,   "x":40,   "l":3,    "b":"O'Zorgnax's Pub"                             },
                    { "n":"Destroy a Wall",                             "d":"P0T03:00:00",  "c":80,   "x":54,   "l":4,    "b":"Planet Express Building"                     },
                    { "n":"Answer the Telephones",                      "d":"P0T04:00:00",  "c":95,   "x":60,   "l":13,   "b":"Satellite Building"                          },
                    { "n":"Flip Over a Car",                            "d":"P0T04:00:00",  "c":95,   "x":60,   "l":10,   "b":"Malfunctioning Eddie's Rocket Car Emporium"  },
                    { "n":"Wake Up the Tenants",                        "d":"P0T04:00:00",  "c":95,   "x":60,   "l":7,    "b":"Robot Arms Apts."                            },
                    { "n":"Wrestle to the Death",                       "d":"P0T00:00:00",  "c":0,    "x":0,    "l":1,    "h":"Bender"                                      },
                    { "n":"Break the Buffet Tables",                    "d":"P0T06:00:00",  "c":125,  "x":85,   "l":11,   "b":"Electric Ladyland"                           },
                    { "n":"Breakdance",                                 "d":"P0T06:00:00",  "c":125,  "x":85,   "l":7     },
                    { "n":"Ransack the Merchandise",                    "d":"P0T06:00:00",  "c":125,  "x":85,   "l":8,    "b":"Rook Takes Pawnshop"                         },
                    { "n":"Free the Convicts",                          "d":"P0T08:00:00",  "c":155,  "x":105,  "l":14,   "b":"NNYPD Precinct"                              },
                    { "n":"Scare the Guests",                           "d":"P0T08:00:00",  "c":155,  "x":105,  "l":9,    "b":"New New York Plaza"                          },
                    { "n":"Trash the Aisles",                           "d":"P0T08:00:00",  "c":155,  "x":105,  "l":5,    "b":"7^11"                                        },
                    { "n":"Yell His Name",                              "d":"P0T08:00:00",  "c":155,  "x":105,  "l":12,   "b":"Modest Business Building"                    },
                    { "n":"Act Like a Bull in a China Shop",            "d":"P0T12:00:00",  "c":200,  "x":130,  "l":16,   "b":"Diamonds are Forever"                        }
                ]
            ],
        '28' : [ "Dr. Cahill",                 null,                 1, 0, 1, 
            ],
        '29' : [ "Mutant Dwayne",              null,                 4, 0, 1, 
            ],
        '30' : [ "Fender",                     null,                 2, 0, 0, 
            ],
        '31' : [ "Flexo",                      null,                 2, 0, 1, 
            ],
        '32' : [ "Free Waterfall Jr.",         null,                 3, 0, 0, 
            ],
        '33' : [ "Fry",                        null,                 3, 1, 0, 
            ],
        '34' : [ "Fry",                        "Bachelor",           4, 0, 0, 
            ],
        '35' : [ "Fry",                        "Devilish",           0, 0, 0, 
            ],
        '77' : [ "Fry",                        "Power Suit",         3, 0, 2, 
            ],
        '36' : [ "Fry",                        "Robot",              2, 0, 0, 
            ],
        '37' : [ "Fry",                        "Slurm Duke",         4, 0, 0, 
            ],
        '38' : [ "George Takei",               null,                 0, 0, 1, 
            ],
        '39' : [ "Hattie McDoogal",            null,                 0, 0, 0, 
            ],
        '40' : [ "Hedonismbot",                null,                 2, 0, 0, 
            ],
        '41' : [ "Hermes",                     null,                 4, 0, 0, 
            ],
        '42' : [ "Hermes",                     "Mecha",              2, 0, 1, 
            ],
        '43' : [ "Horrible Gelatinous Blob",   null,                 3, 0, 1, 
            ],
        '44' : [ "Hookerbot",                  null,                 2, 0, 0, 
            ],
        '45' : [ "The Professor",              null,                 1, 1, 0, 
            ],
        '46' : [ "The Professor",              "Colonial",           0, 0, 0, 
            ],
        '47' : [ "Hyper-Chicken",              null,                 4, 0, 1, 
            ],
        '48' : [ "Kif",                        null,                 3, 0, 2, 
            ],
        '49' : [ "Kif",                        "Cowboy",             3, 0, 2, 
            ],
        '50' : [ "LaBarbara",                  null,                 4, 0, 1, 
            ],
        '51' : [ "Leela",                      null,                 0, 0, 2, 
            ],
        '52' : [ "Leela",                      "Colonial",           3, 0, 2, 
            ],
        '53' : [ "Leela",                      "Lee Lemon",          3, 0, 2, 
            ],
        '54' : [ "Leela",                      "Robot",              2, 0, 2, 
            ],
        '55' : [ "Leg Mutant",                 null,                 3, 0, 0, 
            ],
        '56' : [ "Lrrr",                       null,                 0, 0, 2, 
            ],
        '57' : [ "Malfunctioning Eddie",       null,                 3, 0, 0, 
            ],
        '58' : [ "Monique",                    null,                 4, 0, 2, 
            ],
        '61' : [ "Ndnd",                       null,                 4, 0, 2, 
            ],
        '59' : [ "Neil deGrasse Tyson",        null,                 1, 0, 0, 
            ],
        '60' : [ "Nixon & Agnew",              null,                 0, 0, 2, 
            ],
        '62' : [ "Pazuzu",                     null,                 3, 0, 1, 
            ],
        '63' : [ "Mr. Peppy",                  null,                 3, 0, 3, 
            ],
        '64' : [ "Lionel Preacherbot",         null,                 2, 0, 0, 
            ],
        '65' : [ "Roberto",                    null,                 5, 0, 1, 
            ],
        '66' : [ "Robot Devil",                null,                 5, 0, 2, 
            ],
        '67' : [ "Robot Gypsy",                null,                 4, 0, 2, 
            ],
        '68' : [ "Scruffy",                    null,                 4, 0, 1, 
            ],
        '69' : [ "Slurms McKenzie",            null,                 0, 0, 0, 
            ],
        '70' : [ "Smitty",                     null,                 3, 0, 1, 
            ],
        '71' : [ "Stephen Hawking",            null,                 1, 0, 2, 
            ],
        '75' : [ "Tinny Tim",                  null,                 3, 0, 0, 
            ],
        '72' : [ "URL",                        null,                 2, 0, 1, 
            ],
        '73' : [ "URL",                        "Off-duty",           3, 0, 1, 
            ],
        '74' : [ "Mutant Vyolet",              null,                 3, 0, 0, 
            ]
    };